=== Makkras2002/JavaTask3/sourcefile/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.task3.org/cards" xmlns:tns="http://www.task3.org/cards">

    <element name="cards">
        <complexType>
            <sequence>
                <element ref="tns:post-card" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <complexType name="card">
        <sequence>
            <element name="theme" type="tns:themes" />
            <element name="year" type="gYear" />
            <element name="valuable" type="tns:valuables" />
        </sequence>
        <attribute name="id" type="tns:cardId" use="required"/>
        <attribute name="was-sent" type="boolean" use="optional" default="true"/>
    </complexType>

    <complexType name="compact-post-card-type">
        <complexContent>
            <extension base="tns:card">
                <sequence>
                    <element name="compact-post-code" type="tns:code-format"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="extended-post-card-type">
        <complexContent>
            <extension base="tns:card">
                <sequence>
                    <element name="card-type" type="tns:card-types" />
                    <element name="country" type="tns:countries" />
                    <element name="author" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="cardId">
        <restriction base="ID">
            <pattern value="\w{1,10}"/>
        </restriction>
    </simpleType>

    <simpleType name="code-format">
        <restriction base="unsignedInt">
            <minInclusive value="0"/>
            <maxInclusive value="40000"/>
        </restriction>
    </simpleType>


    <simpleType name="themes">
        <restriction base="string">
            <enumeration value="CITYSCAPE" />
            <enumeration value="NATURE" />
            <enumeration value="PEOPLE" />
            <enumeration value="RELIGION" />
            <enumeration value="SPORT" />
            <enumeration value="ARCHITECTURE" />
        </restriction>
    </simpleType>

    <simpleType name="valuables">
        <restriction base="string">
            <enumeration value="HISTORICAL" />
            <enumeration value="COLLECTIBLE" />
            <enumeration value="THEMATIC" />
        </restriction>
    </simpleType>

    <simpleType name="card-types">
        <restriction base="string">
            <enumeration value="CONGRATULATORY" />
            <enumeration value="ADVERTISING" />
            <enumeration value="REGULAR" />
        </restriction>
    </simpleType>

    <simpleType name="countries">
        <restriction base="string">
            <enumeration value="RUSSIA" />
            <enumeration value="BELARUS" />
            <enumeration value="POLAND" />
            <enumeration value="GERMANY" />
            <enumeration value="USA" />
            <enumeration value="CANADA" />
            <enumeration value="UK" />
            <enumeration value="FRANCE" />
        </restriction>
    </simpleType>


    <element name="post-card" type="tns:card" abstract="true" />
    <element name="compact-post-card" type="tns:compact-post-card-type" substitutionGroup="tns:post-card"/>
    <element name="extended-post-card" type="tns:extended-post-card-type" substitutionGroup="tns:post-card"/>
</schema>

=== Makkras2002/JavaTask3/sourcefile/pcard.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.task3.org/cards"
       xsi:schemaLocation="http://www.task3.org/cards schema.xsd">
  <compact-post-card id="cpc1">
    <theme> RELIGION</theme>
    <year>1905</year>
    <valuable> HISTORICAL</valuable>
    <compact-post-code> 20054kpk</compact-post-code>
  </compact-post-card>
  <extended-post-card id="epc1">
    <theme> PEOPLE</theme>
    <year> 1944</year>
    <valuable> COLLECTIBLE</valuable>
    <card-type> CONGRATULATORY</card-type>
    <country> GERMANY</country>
    <author> Iron Hans</author>
  </extended-post-card>
</cards>
